export const homeAdvantages =
  ["Wi-Fi and Bluetooth Connectivity",
    "Safe & Weatherproof",
    "Low-Cost Charging Device",
    "Easy-to-Use Ergonomic Interface",
    "20% Faster than Competing Devices",
    "Simple Installation",
    "Compact Form Factor",
    "Simple Scan-Pay-Charge",
    "Money-Saving Home Charging",
    "One-Time Installation",
    "Simple installation",
    "Trackable Charging Sessions on the BOLT App",
    "Extensive Charging Network ",
    "Convenient BOLT OS navigation feature",
    "Intelligent Power Management"]

export const buildingAdvantages = [
  "Increase your property value",
  "Convenient EV charging at your own apartment or condo",
  "Automated booking and payments",
  "Sleek design",
  "All-in-one BOLT app",
  "Truly passive income",
  "Low-cost devices",
  "High-performance charging",
  "Weather-resistant hardware",
  "Simple installation",
  "Money-saving with potential property tax exemptions",
  "Compatible with all EVs",
  "Easy transition to pollution-free living"
]

export const faq = [
  {
    id:1,
    question:"What is Bolt?",
    answer:"BOLT is India's largest peer-to-peer EV charging network. We aim to make EV charging in India more accessible to everyone. Watch our TVC at <a href='https://bit.ly/3s4FPEd'>https://bit.ly/3s4FPEd</a> or visit <a href='www.bolt.earth'>www.bolt.earth</a>.",
  },
  {
    id:2,
    question:"What vehicles does BOLT support?",
    answer:"BOLT is compatible with all types of EVs (2-wheelers, 3-wheelers, 4-wheelers, and E-rickshaws)",
  },
  { id:3,
    question:"Does BOLT support fast charging?",
    answer:"BOLT currently supports fast charging for 2- and 3-wheeler EVs, as it depends on the EV's charger specifications. For 4-wheelers, BOLT offers regular charging.",
  },
  { id:4,
    question:"What do I need to install a BOLT charging point?",
    answer:"Install a BOLT charging point anywhere with a dedicated parking space and a standard residential 220V main power supply. You don’t need a specialist commercial multiphase power source for the installation. Simply get a certified electrician to connect the BOLT charging point to your home or office.",
  },
  { id:5,
    question:"How do I place an order for a BOLT charging point?",
    answer:"Fill out the request form found on https://bolt.earth/enquire. You also can buy the BOLT charging point from Amazon and Flipkart.",
  },
  { id:6,
    question:"How can I track my order?",
    answer:"Receive your order within 60 days from the day you ordered. It takes 7-14 days for dispatch, following KYC verification. We’ll notify you once we verify your account.",
  },
  { id:7,
    question:"Do BOLT products have a warranty?",
    answer:"We offer a 1-year warranty (from the delivery date of delivery) for our BOLT products.",
  },
  { id:8,
    question:"How do I install the BOLT charger?",
    answer:"Mount the BOLT charger on a wall or any flat surface. It takes less than 30 minutes to install on your own. You also can call an electrician to help you with installation. Watch this installation video for guidance.",
  },
  { id:9,
    question:"Can BOLT staff help with installation or provide a product demonstration?",
    answer:"Yes, depending on your location and need, we can help you with installation remotely or in person. For further assistance, call us at +91-844-774-6385, toll-free. We’re available from 9 AM to 9 PM IST (Monday to Saturday).",
  },
  { id:10,
    question:"How can I locate the charger nearest to me?",
    answer:"Use the BOLT application to locate the nearest BOLT charging point. Download the BOLT app from the Google Play Store or the Apple App Store. Then, create an account, and you’re good to go!",
  },
  { id:11,
    question:"How can I earn using BOLT?",
    answer:"BOLT lets EV and non-EV users earn passive income. Mark your charger Public and share it with other EV users. The BOLT charging points are an investment opportunity if you want to make a passive income. Contact us to learn more!",
  },
];